### PR TITLE
 LRDOCS-7959 Upgrading to a new docker image

### PR DESCRIPTION
**Pull request by jhinkey**
Here is some wordsmithing. thanks!

### CODE REVIEW

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
Hey @jhinkey,

It looks great to me. I don't have any modification to add :-)

Thanks!

**Comment by jhinkey** [comment]
Alberto, Thank you for the care you've taken to make these documents accurate and efficient for the user to execute. :-)

**Comment by jhinkey** [comment]
Sent the changes via https://github.com/sez11a/liferay-learn/pull/143

**Pull request closed without merging**
