### PR TITLE
Upgrade database auto run

### PR DESCRIPTION
**Pull request by jhinkey**
Hi Alberto,

I updated the sysadmin/deployment docs based on your comments. Can you check the changes I made, starting with the commits today on Feb 4th?

### CODE REVIEW

**Comment by jhinkey** [comment]
@achaparro - Let me know how these changes are. Thanks!

**Comment by achaparro** [comment]
Hey @jhinkey, they look great! Thanks!

**Comment by achaparro** [comment]
Should I send the changes to someone? @jhinkey

**Comment by jhinkey** [comment]
Thanks. I sent https://github.com/jrhoun/liferay-learn/pull/195

**Pull request closed without merging**
