### PR TITLE
LRDOCS-9331 Upgrading Marketplace apps

### PR DESCRIPTION
**Pull request by jhinkey**
Hi Alberto, 

I updated upgrade-overview.md to describe app upgrades more generally and I moved the details to the Docker and Upgrade Tool articles. Let me know what you think. Thanks.

cc/ @ricardocousolr

### CODE REVIEW

**Comment by jhinkey** [comment]
Hi @achaparro !

Does this look good to you?

**Comment by achaparro** [comment]
Hi @jhinkey,

It looks amazing! great job :-)

I will close it but you move it forward.

Thanks!

cc/@ricardocousolr

**Comment by jhinkey** [comment]
Thanks you, @achaparro ! :-)

**Comment by ricardocousolr** [comment]
Thanks!

**Comment by jhinkey** [comment]
Sent in https://github.com/jrhoun/liferay-learn/pull/1013

**Pull request closed without merging**
